//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.02.13 at 02:58:03 PM EST 
//


package org.publisher.elsevier.xml;

public interface Date {


    /**
     * Gets the value of the day property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    java.lang.String getDay();

    /**
     * Sets the value of the day property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    void setDay(java.lang.String value);

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getYear();

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setYear(java.lang.String value);

    /**
     * Gets the value of the month property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    java.lang.String getMonth();

    /**
     * Sets the value of the month property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    void setMonth(java.lang.String value);

}
