//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.02.13 at 02:58:03 PM EST 
//


package org.publisher.elsevier.xml;

import javax.xml.bind.JAXBException;
import javax.xml.bind.PropertyException;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.publisher.elsevier.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends org.publisher.elsevier.xml.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(16, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static org.publisher.elsevier.xml.impl.runtime.GrammarInfo grammarInfo = new org.publisher.elsevier.xml.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (org.publisher.elsevier.xml.ObjectFactory.class));
    public final static java.lang.Class version = (org.publisher.elsevier.xml.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((org.publisher.elsevier.xml.Dataset.class), "org.publisher.elsevier.xml.impl.DatasetImpl");
        defaultImplementations.put((org.publisher.elsevier.xml.Date.class), "org.publisher.elsevier.xml.impl.DateImpl");
        defaultImplementations.put((org.publisher.elsevier.xml.File.class), "org.publisher.elsevier.xml.impl.FileImpl");
        rootTagMap.put(new javax.xml.namespace.QName("", "file"), (org.publisher.elsevier.xml.File.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "dataset"), (org.publisher.elsevier.xml.Dataset.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "date"), (org.publisher.elsevier.xml.Date.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.publisher.elsevier.xml
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of Dataset
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.publisher.elsevier.xml.Dataset createDataset()
        throws javax.xml.bind.JAXBException
    {
        return new org.publisher.elsevier.xml.impl.DatasetImpl();
    }

    /**
     * Create an instance of Date
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.publisher.elsevier.xml.Date createDate()
        throws javax.xml.bind.JAXBException
    {
        return new org.publisher.elsevier.xml.impl.DateImpl();
    }

    /**
     * Create an instance of File
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.publisher.elsevier.xml.File createFile()
        throws javax.xml.bind.JAXBException
    {
        return new org.publisher.elsevier.xml.impl.FileImpl();
    }

}
