

alter table cat_contracts
drop
(CAT_RVSD_PREAMBLE_SEC ,
CAT_RVSD_DEFINITIONS_SEC ,
CAT_RVSD_GRANT_OF_LICENSE_SEC ,
CAT_RVSD_PRES_AND_DISTR_SEC ,
CAT_RVSD_IP_OWNERHIP_SEC ,
CAT_RVSD_LTD_TM_LICENSE_SEC ,
CAT_RVSD_REP_AND_WRNTY_SEC ,
CAT_RVSD_TERM_SEC ,
CAT_RVSD_REVENUE_SHARING_SEC ,
CAT_RVSD_CONFIDENTIALITY_SEC ,
CAT_RVSD_DLVRY_OF_PUBLCTN_SEC ,
CAT_RVSD_GOVERNING_LAW_SEC ,
CAT_RVSD_NOTICES_SEC ,
CAT_RVSD_CONTRACT_MISC_SEC);

alter table cat_contracts
add
(     CAT_RVSD_PREAMBLE_SEC CLOB  NULL , 
     CAT_RVSD_DEFINITIONS_SEC CLOB  NULL , 
     CAT_RVSD_GRANT_OF_LICENSE_SEC CLOB  NULL , 
     CAT_RVSD_PRES_AND_DISTR_SEC CLOB  NULL , 
     CAT_RVSD_IP_OWNERHIP_SEC CLOB  NULL , 
     CAT_RVSD_LTD_TM_LICENSE_SEC CLOB  NULL , 
     CAT_RVSD_REP_AND_WRNTY_SEC CLOB  NULL , 
     CAT_RVSD_TERM_SEC CLOB  NULL , 
     CAT_RVSD_REVENUE_SHARING_SEC CLOB  NULL , 
     CAT_RVSD_CONFIDENTIALITY_SEC CLOB  NULL , 
     CAT_RVSD_DLVRY_OF_PUBLCTN_SEC CLOB  NULL , 
     CAT_RVSD_GOVERNING_LAW_SEC CLOB  NULL , 
     CAT_RVSD_NOTICES_SEC CLOB  NULL , 
     CAT_RVSD_CONTRACT_MISC_SEC CLOB  NULL ) ;

alter table a_cat_contracts
drop
(CAT_RVSD_PREAMBLE_SEC ,
CAT_RVSD_DEFINITIONS_SEC ,
CAT_RVSD_GRANT_OF_LICENSE_SEC ,
CAT_RVSD_PRES_AND_DISTR_SEC ,
CAT_RVSD_IP_OWNERHIP_SEC ,
CAT_RVSD_LTD_TM_LICENSE_SEC ,
CAT_RVSD_REP_AND_WRNTY_SEC ,
CAT_RVSD_TERM_SEC ,
CAT_RVSD_REVENUE_SHARING_SEC ,
CAT_RVSD_CONFIDENTIALITY_SEC ,
CAT_RVSD_DLVRY_OF_PUBLCTN_SEC ,
CAT_RVSD_GOVERNING_LAW_SEC ,
CAT_RVSD_NOTICES_SEC ,
CAT_RVSD_CONTRACT_MISC_SEC);

alter table a_cat_contracts
add
(     CAT_RVSD_PREAMBLE_SEC CLOB  NULL , 
     CAT_RVSD_DEFINITIONS_SEC CLOB  NULL , 
     CAT_RVSD_GRANT_OF_LICENSE_SEC CLOB  NULL , 
     CAT_RVSD_PRES_AND_DISTR_SEC CLOB  NULL , 
     CAT_RVSD_IP_OWNERHIP_SEC CLOB  NULL , 
     CAT_RVSD_LTD_TM_LICENSE_SEC CLOB  NULL , 
     CAT_RVSD_REP_AND_WRNTY_SEC CLOB  NULL , 
     CAT_RVSD_TERM_SEC CLOB  NULL , 
     CAT_RVSD_REVENUE_SHARING_SEC CLOB  NULL , 
     CAT_RVSD_CONFIDENTIALITY_SEC CLOB  NULL , 
     CAT_RVSD_DLVRY_OF_PUBLCTN_SEC CLOB  NULL , 
     CAT_RVSD_GOVERNING_LAW_SEC CLOB  NULL , 
     CAT_RVSD_NOTICES_SEC CLOB  NULL , 
     CAT_RVSD_CONTRACT_MISC_SEC CLOB  NULL ) ;

