CREATE TABLE  "REVINFO" 
   (    "REV" NUMBER(10,0) NOT NULL ENABLE, 
    "REVTSTMP" NUMBER(19,0), 
     PRIMARY KEY ("REV") ENABLE
   )
;
CREATE TABLE  "A_CAT_ACQ_ORDERS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_COMPLETED_BY" VARCHAR2(255 CHAR), 
   "CAT_COVER_DATE_RANGE" VARCHAR2(255 CHAR), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_COMPLETED" DATE, 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_LEGACY_SUBSCRIPTION_NOTE" CLOB, 
   "CAT_LIFECYCLE" VARCHAR2(255 CHAR), 
   "CAT_NOT_RECEIVED_NOTE" CLOB, 
   "CAT_NOTIFICATION_THRESHOLD" NUMBER(5,0), 
   "CAT_ON_HOLD" CHAR(1 CHAR), 
   "CAT_ON_HOLD_REASON" CLOB, 
   "CAT_OUTCOME" VARCHAR2(255 CHAR), 
   "CAT_POST_MASTER_ADDRESS" VARCHAR2(2000 CHAR), 
   "CAT_PUBLCTN_UNIT_RANGE" VARCHAR2(100 CHAR), 
   "CAT_QUANTITY" VARCHAR2(255 CHAR), 
   "CAT_REPRINTS" VARCHAR2(255 CHAR), 
   "CAT_RETURN_OBLIGATION" VARCHAR2(255 CHAR), 
   "CAT_SUPPLIER" VARCHAR2(1000 CHAR), 
   "CAT_SUPPLIER_COMMITMENT" VARCHAR2(255 CHAR), 
   "CAT_SUPPLIER_CONTACT" VARCHAR2(2000 CHAR), 
   "CAT_TYPE" VARCHAR2(255 CHAR), 
   "CAT_CMPT_ID" VARCHAR2(255 CHAR), 
   "CAT_SET_ID" VARCHAR2(255 CHAR), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FKF19F149CDF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_ACQ_ORDERS_NOTE" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_NOTE" CLOB, 
   "CAT_TYPE" VARCHAR2(255 CHAR), 
   "CAT_ACQ_ORDERS_ID" VARCHAR2(255 CHAR), 
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK6A40CDB5DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_ACQ_ORDERS_PROBLEMS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_DATE_RESOLVED" DATE, 
   "CAT_LIFECYCLE" VARCHAR2(255 CHAR), 
   "CAT_NOTE" CLOB, 
   "CAT_OUTCOME" VARCHAR2(255 CHAR), 
   "CAT_RESOLUTION_EFFORT" VARCHAR2(255 CHAR), 
   "CAT_RESOLVED_BY" VARCHAR2(255 CHAR), 
   "CAT_TYPE" VARCHAR2(255 CHAR), 
   "CAT_ACQ_ORDERS_ID" VARCHAR2(255 CHAR), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK2EF0DF7DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_CMPTS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_ACQ_DATE_COMPLETED" DATE, 
   "CAT_ACQ_DATE_STARTED" DATE, 
   "CAT_ART_DARK_NOTE" CLOB, 
   "CAT_ART_DARK_NOTE_CHANGE_BY" VARCHAR2(255 CHAR), 
   "CAT_ART_DARK_NOTE_DATE_CHANGE" TIMESTAMP (6), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_CRNT_RELEASED_PAGE_CNT" NUMBER(19,0), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_DATE_RANGE" VARCHAR2(200 CHAR), 
   "CAT_DATE_SENT_TO_VENDOR" DATE, 
   "CAT_E_ISSN" VARCHAR2(14 CHAR), 
   "CAT_END_DATE_IS_AN_ESTIMATE" CHAR(1 CHAR), 
   "CAT_EXCLUDED_RANGE" VARCHAR2(500 CHAR), 
   "CAT_GRANT_CODE" VARCHAR2(255 CHAR), 
   "CAT_IMG_DARK_NOTE" CLOB, 
   "CAT_IMG_DARK_NOTE_CHANGE_BY" VARCHAR2(255 CHAR), 
   "CAT_IMG_DARK_NOTE_DATE_CHANGE" TIMESTAMP (6), 
   "CAT_INCLUDE_IN_HCL_REPOSITORY" CHAR(1 CHAR), 
   "CAT_INCLUDE_IN_UC_REPOSITORY" VARCHAR2(255 CHAR), 
   "CAT_INI_ART" VARCHAR2(20 CHAR), 
   "CAT_INI_CIL_RELEASE_STATUS" VARCHAR2(255 CHAR), 
   "CAT_INI_RELEASE_DATE_ACTL" DATE, 
   "CAT_INI_RELEASE_DATE_PRJD" DATE, 
   "CAT_INI_RELEASE_DATE_SCHD" DATE, 
   "CAT_INI_RELEASE_DEADLINE" DATE, 
   "CAT_INI_RELEASE_PAGE_CNT" NUMBER(19,0), 
   "CAT_ISSN_DATE_RECEIVED" DATE, 
   "CAT_ISSN_DATE_REQUESTED" DATE, 
   "CAT_ISSN_NOTE" CLOB, 
   "CAT_ISSN_NOTE_CHANGE_BY" VARCHAR2(255 CHAR), 
   "CAT_ISSN_NOTE_DATE_CHANGE" DATE, 
   "CAT_ISSN_REQUEST_NOTE" CLOB, 
   "CAT_ISSN_REQUESTED_BY" VARCHAR2(255 CHAR), 
   "CAT_ISSN_STATUS" VARCHAR2(255 CHAR), 
   "CAT_LIFECYCLE" VARCHAR2(255 CHAR), 
   "CAT_LIST_ON_BIN" CHAR(1 CHAR), 
   "CAT_LTM_JOURNAL_CODE" VARCHAR2(50 CHAR), 
   "CAT_LTM_JOURNAL_ID" VARCHAR2(50 CHAR), 
   "CAT_NAME" VARCHAR2(500 CHAR), 
   "CAT_NEEDED_SOURCE_CHANGE_BY" VARCHAR2(255 CHAR), 
   "CAT_NEEDED_SOURCE_DATE_CHANGE" TIMESTAMP (6), 
   "CAT_NEEDED_SOURCE_LIST" CLOB, 
   "CAT_ON_HOLD" CHAR(1 CHAR), 
   "CAT_ON_HOLD_REASON" CLOB, 
   "CAT_PARTICIPATION_DATE" DATE, 
   "CAT_PRIMARY_SIG_AUTHOR" VARCHAR2(255 CHAR), 
   "CAT_PRIMARY_SIG_DATE_COMPLETED" DATE, 
   "CAT_PRINT_ISSN" VARCHAR2(50 CHAR), 
   "CAT_PRODUCTION_NOTE" CLOB, 
   "CAT_PRODUCTION_STATUS" VARCHAR2(255 CHAR), 
   "CAT_PUBLCTN_UNIT_RANGE" VARCHAR2(200 CHAR), 
   "CAT_PUBLISHER_SPECIFIED_NAME" CHAR(1 CHAR), 
   "CAT_RIGHTS_EXCLUSIONS" CHAR(1 CHAR), 
   "CAT_RIGHTS_OBTAINED" CHAR(1 CHAR), 
   "CAT_RIGHTS_OBTAINED_BY" VARCHAR2(255 CHAR), 
   "CAT_RIGHTS_OBTAINED_DATE" TIMESTAMP (6), 
   "CAT_SELECTION_RECOMMENDATION" VARCHAR2(255 CHAR), 
   "CAT_SELECTION_STATUS" VARCHAR2(255 CHAR), 
   "CAT_SIGNING_DEADLINE_DATE" DATE, 
   "CAT_START_DATE_IS_AN_ESTIMATE" CHAR(1 CHAR), 
   "CAT_SUBTITLE" VARCHAR2(4000 CHAR), 
   "CAT_TH_OCLC_NUMBER" VARCHAR2(50 CHAR), 
   "CAT_TITLE_ISSN" VARCHAR2(14 CHAR), 
   "CAT_UPDATE_BIN" CHAR(1 CHAR), 
   "CAT_WEB_ATTRIBUTION_OVERRIDE" CLOB, 
   "CAT_DIGI_VENDOR_ID" VARCHAR2(255 CHAR), 
   "CAT_START_YEAR" DATE,
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FKA4E401DEDF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_CMPTS_TO_DISCIPLINES" 
  (    "CAT_CMPT_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "CAT_DISCIPLINES_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_ORDINAL" NUMBER(10,0), 
    PRIMARY KEY ("CAT_CMPT_ID", "CAT_DISCIPLINES_ID", "REV") ENABLE, 
    CONSTRAINT "FKA9D1A3A0DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_CMPT_TAGS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_NAME" VARCHAR2(255 CHAR), 
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FKAE042903DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_CMPT_TAGS_TO_CMPTS" 
  (    "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "CAT_CMPTS_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "CAT_CMPT_TAGS_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
    PRIMARY KEY ("REV", "CAT_CMPTS_ID", "CAT_CMPT_TAGS_ID") ENABLE, 
    CONSTRAINT "FK8ABB3F1DDF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_COLLECTIONS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_ANNCMNT_DATE_ACTL" DATE, 
   "CAT_ANNCMNT_DATE_PRJD" DATE, 
   "CAT_ANNCMNT_DATE_SCHD" DATE, 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_LAUNCH_DATE_ACTL" DATE, 
   "CAT_LAUNCH_DATE_PRJD" DATE, 
   "CAT_LAUNCH_DATE_SCHD" DATE, 
   "CAT_LIFECYCLE" VARCHAR2(255 CHAR), 
   "CAT_MIN_PROM_CMPLTN_DATE_ACTL" DATE, 
   "CAT_MIN_PROM_CMPLTN_DATE_PRJD" DATE, 
   "CAT_MIN_PROM_CMPLTN_DATE_SCHD" DATE, 
   "CAT_MIN_PROM_SET_CNT" NUMBER(10,0), 
   "CAT_MIN_PROM_SIGNING_DEADLINE" DATE, 
   "CAT_NAME" VARCHAR2(100 CHAR), 
   "CAT_OTHER_PROM_CONTENT_NOTE" CLOB, 
   "CAT_PAGE_BUDGET" NUMBER(19,0), 
   "CAT_TARGET_SET_CNT" NUMBER(10,0), 
   "CAT_TYPE" VARCHAR2(255 CHAR), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK1ABDEE6EDF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_COLLECTION_CHANGE_HIST" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_CHANGE_BY" VARCHAR2(255 CHAR), 
   "CAT_CHANGE_TYPE" VARCHAR2(255 CHAR), 
   "CAT_DATE_CHANGE" TIMESTAMP (6), 
   "CAT_OLD_VALUE" VARCHAR2(1000 CHAR), 
   "CAT_REASON" CLOB, 
   "CAT_COLLECTION_ID" VARCHAR2(255 CHAR), 
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FKAEFDF797DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_COLLECTION_NOTE" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_NOTE" CLOB, 
   "CAT_TYPE" VARCHAR2(255 CHAR), 
   "CAT_COLLECTION_ID" VARCHAR2(255 CHAR), 
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK94F2C96CDF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_CONTRACTS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_AGREEMENT_DATE" DATE, 
   "CAT_AGREEMENT_REVISIONS" CHAR(1 CHAR), 
   "CAT_AGREEMENT_VERSION" VARCHAR2(255 CHAR), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_LIFECYCLE" VARCHAR2(255 CHAR), 
   "CAT_NOTE" CLOB, 
   "CAT_NOTE_CHANGE_BY" VARCHAR2(255 CHAR), 
   "CAT_NOTE_CHANGE_DATE" TIMESTAMP (6), 
   "CAT_ON_HOLD" CHAR(1 CHAR), 
   "CAT_ON_HOLD_REASON" CLOB, 
   "CAT_OUTCOME" VARCHAR2(255 CHAR), 
   "CAT_RVSD_CONFIDENTIALITY_SEC" CLOB  NULL, 
   "CAT_RVSD_CONTRACT_MISC_SEC" CLOB  NULL, 
   "CAT_RVSD_DEFINITIONS_SEC" CLOB  NULL, 
   "CAT_RVSD_DLVRY_OF_PUBLCTN_SEC" CLOB  NULL, 
   "CAT_RVSD_GOVERNING_LAW_SEC" CLOB  NULL, 
   "CAT_RVSD_GRANT_OF_LICENSE_SEC" CLOB  NULL, 
   "CAT_RVSD_IP_OWNERHIP_SEC" CLOB  NULL, 
   "CAT_RVSD_LTD_TM_LICENSE_SEC" CLOB  NULL, 
   "CAT_RVSD_NOTICES_SEC" CLOB  NULL, 
   "CAT_RVSD_PREAMBLE_SEC" CLOB  NULL, 
   "CAT_RVSD_PRES_AND_DISTR_SEC" CLOB  NULL, 
   "CAT_RVSD_REP_AND_WRNTY_SEC" CLOB  NULL, 
   "CAT_RVSD_REVENUE_SHARING_SEC" CLOB  NULL, 
   "CAT_RVSD_TERM_SEC" CLOB  NULL, 
   "CAT_SHAREPOINT_CONTRACT_LINK" VARCHAR2(1000 CHAR), 
   "CAT_TERMINATION_DATE" DATE, 
   "CAT_PUBLISHER_ID" VARCHAR2(255 CHAR), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK133A40BADF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_CONTRACT_DTLS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_ALL_OR_PART_OF_CMPT" VARCHAR2(255 CHAR), 
   "CAT_CONTENT_COVERED" VARCHAR2(1000 CHAR), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_EFFECTIVE_DATE" DATE, 
   "CAT_ITHAKA_AS_LICENSOR_REASON" VARCHAR2(255 CHAR), 
   "CAT_LIFECYCLE" VARCHAR2(255 CHAR), 
   "CAT_OUTCOME" VARCHAR2(255 CHAR), 
   "CAT_PSS_EXCLUDED_ARTS" CLOB, 
   "CAT_PSS_EXCLUSIONS" CHAR(1 CHAR), 
   "CAT_PUBLISHER_USE_OF_FILES" CLOB, 
   "CAT_TERMINATION_DATE" DATE, 
   "CAT_CMPT_ID" VARCHAR2(255 CHAR), 
   "CAT_CONTRACT_ID" VARCHAR2(255 CHAR), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK77209BDDDF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_CONTRACT_DTLS_NOTE" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_NOTE" CLOB, 
   "CAT_TYPE" VARCHAR2(255 CHAR), 
   "CAT_CONTRACT_DTLS_ID" VARCHAR2(255 CHAR), 
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FKFA86A714DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_DIGI_VENDOR_LIST" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_NAME" VARCHAR2(255 CHAR), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FKADFAB3C4DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_DISCIPLINES" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_NAME" VARCHAR2(50 CHAR), 
   "CAT_TYPE" VARCHAR2(255 CHAR),
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK46359BDCDF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_INVITATIONS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_COMPLETED_BY" VARCHAR2(255 CHAR), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_COMPLETED" TIMESTAMP (6), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_INVITATION_DATE_SENT" DATE, 
   "CAT_ITHAKA_AS_PUBLISHER_REASON" VARCHAR2(255 CHAR), 
   "CAT_LIFECYCLE" VARCHAR2(255 CHAR), 
   "CAT_NEGOTIATOR" VARCHAR2(255 CHAR), 
   "CAT_ON_HOLD" CHAR(1 CHAR), 
   "CAT_ON_HOLD_REASON" CLOB, 
   "CAT_OUTCOME" VARCHAR2(255 CHAR), 
   "CAT_PARTICIPATION_LIKELIHOOD" VARCHAR2(255 CHAR), 
   "CAT_REASON_DECLINED" VARCHAR2(255 CHAR), 
   "CAT_REASON_DECLINED_NOTE" CLOB, 
   "CAT_PUBLISHER_ID" VARCHAR2(255 CHAR), 
   "CAT_SETS_ID" VARCHAR2(255 CHAR), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK4CED44D3DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_INVITATION_NOTE" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_NOTE" CLOB, 
   "CAT_TYPE" VARCHAR2(255 CHAR), 
   "CAT_INVITATION_ID" VARCHAR2(255 CHAR), 
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FKD9166551DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_ISSUE_SHIPMENTS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_COMPLETED_BY" VARCHAR2(255 CHAR), 
   "CAT_COVER_DATE_AS_PRINTED" VARCHAR2(255 CHAR), 
   "CAT_COVER_DATE_RANGE" VARCHAR2(255 CHAR), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_COMPLETED" TIMESTAMP (6), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_DISPOSITION" VARCHAR2(255 CHAR), 
   "CAT_LEGACY_DISPOSITION_NOTE" CLOB, 
   "CAT_LIFECYCLE" VARCHAR2(255 CHAR), 
   "CAT_LOAN_RETURN_DATE" DATE, 
   "CAT_LOAN_RETURN_TRACK_NUMBER" VARCHAR2(255 CHAR), 
   "CAT_MATERIAL_FORMAT" VARCHAR2(255 CHAR), 
   "CAT_NOTE" CLOB, 
   "CAT_ON_HOLD" CHAR(1 CHAR), 
   "CAT_ON_HOLD_REASON" CLOB, 
   "CAT_OUTCOME" VARCHAR2(255 CHAR), 
   "CAT_OWNERSHIP" VARCHAR2(255 CHAR), 
   "CAT_PUBLCTN_UNIT_RANGE" VARCHAR2(255 CHAR), 
   "CAT_QUANTITY" VARCHAR2(255 CHAR), 
   "CAT_RETURN_OBLIGATION" VARCHAR2(255 CHAR), 
   "CAT_SOURCE_CONDITION" VARCHAR2(255 CHAR), 
   "CAT_ACQ_ORDER_ID" VARCHAR2(255 CHAR), 
   "CAT_CMPTS_ID" VARCHAR2(255 CHAR), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK8347BA6CDF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_MOVING_WALL_FLIPS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_ALL_IN_REPOSITORY" VARCHAR2(10 CHAR), 
   "CAT_ALL_IN_REPOSITORY_DATE" TIMESTAMP (6), 
   "CAT_CONTENT_RANGE" VARCHAR2(1000 CHAR), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_COMPLETED" TIMESTAMP (6), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_DATE_SENT_TO_VENDOR" DATE, 
   "CAT_DATE_VERIFIED_FOR_FLIP" TIMESTAMP (6), 
   "CAT_FLIP_PUBLCTN_DATE" DATE, 
   "CAT_FLIP_TO_PUBLIC_YEAR" DATE, 
   "CAT_LIFECYCLE" VARCHAR2(255 CHAR), 
   "CAT_ON_HOLD" CHAR(1 CHAR), 
   "CAT_ON_HOLD_REASON" CLOB, 
   "CAT_PRODUCTION_STATUS" VARCHAR2(40 CHAR), 
   "CAT_PUBLCTN_UNIT_CNT" NUMBER(10,0), 
   "CAT_PUBLCTN_UNIT_CNT_NOTE" CLOB, 
   "CAT_CMPT_ID" VARCHAR2(255 CHAR), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FKAE24759BDF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_MOVING_WALL_FLIP_NOTE" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_NOTE" CLOB, 
   "CAT_TYPE" VARCHAR2(20 CHAR), 
   "CAT_MOVING_WALL_FLIP_ID" VARCHAR2(255 CHAR), 
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK7637F219DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_NEEDED_SOURCE_NOTE" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_NOTE" CLOB, 
   "CAT_TYPE" VARCHAR2(255 CHAR), 
   "CAT_CMPT_ID" VARCHAR2(255 CHAR), 
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK205680F3DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_PRORATES" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_PERCENT" NUMBER(5,2), 
   "CAT_SET_CNT" NUMBER(10,0), 
   "CAT_YEAR" NUMBER(5,0), 
   "CAT_COLLECTION_ID" VARCHAR2(255 CHAR), 
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FKCE8BC6ADDF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_PRORATES_CHANGES" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_CHANGE_BY" VARCHAR2(255 CHAR), 
   "CAT_DATE_CHANGE" TIMESTAMP (6), 
   "CAT_REASON" CLOB, 
   "CAT_PRORATE_ID" VARCHAR2(255 CHAR), 
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK170B5F11DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_PUBLISHERS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_CONTACT_INFORMATION" VARCHAR2(500 CHAR), 
   "CAT_COUNTRY" VARCHAR2(255 CHAR), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_DISPLAY_NAME" VARCHAR2(1000 CHAR), 
   "CAT_LAST_OUTRCH_BY" VARCHAR2(255 CHAR), 
   "CAT_LAST_OUTRCH_DATE" DATE, 
   "CAT_LOGO" CHAR(1 CHAR), 
   "CAT_LOGO_PROBLEM" CLOB, 
   "CAT_NAME" VARCHAR2(255 CHAR), 
   "CAT_ORGANIZATION_TYPE" VARCHAR2(255 CHAR), 
   "CAT_OUTRCH_NOTE" CLOB, 
   "CAT_OUTRCH_NOTE_CHANGE_BY" VARCHAR2(255 CHAR), 
   "CAT_OUTRCH_NOTE_CHANGE_DATE" TIMESTAMP (6), 
   "CAT_TALISMA_ID" VARCHAR2(255 CHAR), 
   "CAT_TAX_FORM_STATUS" VARCHAR2(255 CHAR), 
   "CAT_TAX_WITHHOLDING_PERCENT" NUMBER(5,2), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FKA14751DEDF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_PUBLISHERS_TO_CMPTS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_ALL_OR_PART_OF_CMPTS" VARCHAR2(255 CHAR), 
   "CAT_CHANGE_BY" VARCHAR2(255 CHAR), 
   "CAT_CONTENT_COVERED" VARCHAR2(1000 CHAR), 
   "CAT_DATE_CHANGE" TIMESTAMP (6), 
   "CAT_PROMO_MATERIALS_DATE" DATE, 
   "CAT_ROLE" VARCHAR2(255 CHAR), 
   "CAT_CMPT_ID" VARCHAR2(255 CHAR), 
   "CAT_PUBLISHER_ID" VARCHAR2(255 CHAR), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK758DCA2DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_RIDERS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_NAME" VARCHAR2(255 CHAR), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK10F6E0A0DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_RIDERS_TO_CONTRACT_DTLS" 
  (    "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "CAT_CONTRACT_DTLS_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "CAT_RIDERS_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
    PRIMARY KEY ("REV", "CAT_CONTRACT_DTLS_ID", "CAT_RIDERS_ID") ENABLE, 
    CONSTRAINT "FKD6AC001FDF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_ROLES" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_NAME" VARCHAR2(255 CHAR), 
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FKA5B83A56DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_SETS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_ACQ_CONTACT" VARCHAR2(500 CHAR), 
   "CAT_ACQ_KICK_OFF_NOTE" CLOB, 
   "CAT_BOOK_REVIEWS" VARCHAR2(255 CHAR), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_FINAL_ISSUE_TO_SCAN" VARCHAR2(500 CHAR), 
   "CAT_ILLUSTRATION_CONTENT" VARCHAR2(255 CHAR), 
   "CAT_INI_DIGI" VARCHAR2(50 CHAR), 
   "CAT_INI_DIGI_RANGE_TO_SCAN" VARCHAR2(1000 CHAR), 
   "CAT_LEGACY_CD_NOTE" CLOB, 
   "CAT_LEGACY_OLD_AGREEMENT_DATE" DATE, 
   "CAT_LEGACY_SOURCE_SENT_TO_HCL" CLOB, 
   "CAT_LEGACY_TH_NOTE" CLOB, 
   "CAT_LEGACY_WALL_CHANGE_NOTE" CLOB, 
   "CAT_LIFECYCLE" VARCHAR2(255 CHAR), 
   "CAT_NAME" VARCHAR2(500 CHAR), 
   "CAT_OCLC_LIBRARIES_HLD_CNT" NUMBER(10,0), 
   "CAT_ON_GOING_DIGI" CHAR(1 CHAR), 
   "CAT_ON_HOLD" CHAR(1 CHAR), 
   "CAT_ON_HOLD_REASON" CLOB, 
   "CAT_PUBLCTN_FREQUENCY" VARCHAR2(100 CHAR), 
   "CAT_PUBLCTN_STATUS" VARCHAR2(255 CHAR), 
   "CAT_PUBLISHER_E_CRNT_ISSUES" VARCHAR2(255 CHAR), 
   "CAT_REASON_NO_ONGOING_DIGI" VARCHAR2(255 CHAR), 
   "CAT_RVSD_PAGE_CNT_ESTIMATE" NUMBER(19,0), 
   "CAT_SIGNING_DEADLINE_DATE" DATE, 
   "CAT_TH_ASSIGNED_BY" VARCHAR2(255 CHAR), 
   "CAT_TH_ASSIGNED_DATE" DATE, 
   "CAT_TH_AUTHOR" VARCHAR2(255 CHAR), 
   "CAT_TH_CRNT_PUBLISHER" VARCHAR2(4000 CHAR), 
   "CAT_TH_DATE_COMPLETED" DATE, 
   "CAT_TH_DATE_RANGE" VARCHAR2(4000 CHAR), 
   "CAT_TH_DUE_DATE" DATE, 
   "CAT_TH_LANGUAGES" VARCHAR2(4000 CHAR), 
   "CAT_TH_NEGOTIATOR" VARCHAR2(255 CHAR), 
   "CAT_TH_ONLINE_CONTENT_NOTE" CLOB, 
   "CAT_TH_PAGE_CNT" NUMBER(19,0), 
   "CAT_TH_PAGE_CNT_BASED_ON" VARCHAR2(255 CHAR), 
   "CAT_TH_PUBLCTN_UNIT_RANGE" VARCHAR2(4000 CHAR), 
   "CAT_TH_REQUESTED_BY" VARCHAR2(255 CHAR), 
   "CAT_TH_REQUESTED_DATE" DATE, 
   "CAT_TH_STATUS" VARCHAR2(255 CHAR), 
   "CAT_TH_VERSION_CONSULTED" VARCHAR2(255 CHAR), 
   "CAT_CRNT_TITLE_ID" VARCHAR2(255 CHAR), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK3F274978DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_SETS_TO_CMPTS" 
  (    "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "CAT_SET_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "CAT_CMPT_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
    PRIMARY KEY ("REV", "CAT_SET_ID", "CAT_CMPT_ID") ENABLE, 
    CONSTRAINT "FK64ACD248DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_SETS_TO_COLLECTIONS" 
  (    "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "CAT_SET_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "CAT_COLLECTION_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
    PRIMARY KEY ("REV", "CAT_SET_ID", "CAT_COLLECTION_ID") ENABLE, 
    CONSTRAINT "FKDBFF4758DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_SET_NOTE" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_NOTE" CLOB, 
   "CAT_TYPE" VARCHAR2(50 CHAR), 
   "CAT_SET_ID" VARCHAR2(255 CHAR), 
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK5FC38F76DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_SET_TAGS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_NAME" VARCHAR2(255 CHAR), 
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK5FC6139DDF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_SET_TAGS_TO_SET" 
  (    "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "CAT_SETS_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "CAT_SET_TAGS_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
    PRIMARY KEY ("REV", "CAT_SETS_ID", "CAT_SET_TAGS_ID") ENABLE, 
    CONSTRAINT "FK1633D360DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_SOURCE_SENT_TO_HCL" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_BOX_NUMBER" VARCHAR2(100 CHAR), 
   "CAT_CONTENT_RANGE" VARCHAR2(255 CHAR), 
   "CAT_DATE_SHIPPED" DATE, 
   "CAT_NOTE" CLOB, 
   "CAT_SHIPPED_BY" VARCHAR2(255 CHAR), 
   "CAT_CMPT_ID" VARCHAR2(255 CHAR), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK64A9F037DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_TITLE_RLTNSHPS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_FIRST_CMPT_ID" VARCHAR2(255 CHAR), 
   "CAT_SECOND_CMPT_ID" VARCHAR2(255 CHAR), 
   "CAT_TITLE_RLTNSHP_TYPES_ID" VARCHAR2(255 CHAR), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FKB1B089DADF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_TITLE_RLTNSHP_TYPES" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_LTM_MAPPING" VARCHAR2(255 CHAR), 
   "CAT_NAME" VARCHAR2(255 CHAR), 
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK31811633DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_USER_ROLES" 
  (    "CAT_ROLES_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "CAT_USER_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
    PRIMARY KEY ("CAT_ROLES_ID", "CAT_USER_ID", "REV") ENABLE, 
    CONSTRAINT "FKD8B66110DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_WALL_DTLS" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_CEASED_DATE" DATE, 
   "CAT_CHANGE_TYPE" VARCHAR2(255 CHAR), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_DATE_DEPRECATED" DATE, 
   "CAT_EFFECTIVE_DATE" DATE, 
   "CAT_FIXED_DATE" DATE, 
   "CAT_IMPLEMENTATION_DATE_ACTL" DATE, 
   "CAT_IMPLEMENTATION_DATE_PRJD" DATE, 
   "CAT_IMPLEMENTATION_DATE_SCHD" DATE, 
   "CAT_LIFECYCLE" VARCHAR2(255 CHAR), 
   "CAT_MOVING_VALUE" NUMBER(5,0), 
   "CAT_WALL_TYPE" VARCHAR2(255 CHAR), 
   "CAT_SET_ID" VARCHAR2(255 CHAR), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK83880AA5DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_WALL_NOTE" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_NOTE" CLOB, 
   "CAT_TYPE" VARCHAR2(255 CHAR), 
   "CAT_WALL_DTLS_ID" VARCHAR2(255 CHAR), 
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK838C8480DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE TABLE  "A_CAT_WALL_OVERRIDES" 
  (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTYPE" NUMBER(3,0), 
   "CAT_CREATOR" VARCHAR2(255 CHAR), 
   "CAT_DATE_COMPLETED" TIMESTAMP (6), 
   "CAT_DATE_CREATED" TIMESTAMP (6), 
   "CAT_DISPLAY_THROUGH_DATE" DATE, 
   "CAT_LIFECYCLE" VARCHAR2(255 CHAR), 
   "CAT_NOTE" CLOB, 
   "CAT_OUTCOME" VARCHAR2(255 CHAR), 
   "CAT_SET_ID" VARCHAR2(255 CHAR), 
   "CAT_DATE_MODIFIED" TIMESTAMP,
    PRIMARY KEY ("ID", "REV") ENABLE, 
    CONSTRAINT "FK5AD63A39DF74E053" FOREIGN KEY ("REV")
     REFERENCES  "REVINFO" ("REV") ENABLE
  )
;
CREATE SEQUENCE   "HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
;
