ALTER TABLE CRAWLER_CONFIG ADD EXTRACTOR_NAME VARCHAR2(255);
ALTER TABLE CRAWLER_CONFIG ADD JOURNAL_CODE VARCHAR2(255);
ALTER TABLE CRAWLER_CONFIG ADD IS_ACTIVE CHAR(1);
UPDATE CRAWLER_CONFIG SET EXTRACTOR_NAME='MLRPDFExtractor' WHERE PROVIDER='MLR';
UPDATE CRAWLER_CONFIG SET JOURNAL_CODE='monthlylaborrev' WHERE PROVIDER='MLR';
UPDATE CRAWLER_CONFIG SET IS_ACTIVE='Y';
UPDATE CRAWLER_CONFIG SET warc_file_location='/cmjp/EJournalCrawler/Heritrix/Software/heritrix-3.2.0/jobs/monthlylaborrev/latest/warcs' WHERE PROVIDER='MLR';
COMMIT;

ALTER TABLE CRAWLER_FILE_DETAILS ADD CREATED_TIMESTAMP TIMESTAMP(6);
ALTER TABLE CRAWLER_FILE_DETAILS ADD MODIFIED_TIMESTAMP TIMESTAMP(6);