CREATE TABLE "CRAWLER_CONFIG" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PROVIDER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"WARC_FILE_LOCATION" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"DOWNLOAD_DIR_LOCATION" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"PROVIDER_BASE_URL" VARCHAR2(500 BYTE), 
	"RSYNC_COMMAND" VARCHAR2(500 BYTE), 
	"DELETE_FILES_FROM_DOWNLOAD_DIR" VARCHAR2(1 BYTE), 
	 CONSTRAINT "HERITRIX_CRAWL_CONFIG_PK" PRIMARY KEY ("ID")
   );
    
 CREATE TABLE "CRAWLER_FILE_DETAILS" 
    (	"ID" NUMBER NOT NULL ENABLE, 
 	"PROVIDER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
 	"PDF_LINK" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
 	"DESTINATION_FILE_PATH" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
 	"FILE_PUB_DATE" DATE, 
 	"FILE_LAST_MODIFIED" DATE, 
 	"FILE_SIZE" NUMBER, 
 	"FILE_NAME" VARCHAR2(500 BYTE), 
 	"NEW_FILE_NAME" VARCHAR2(500 BYTE), 
 	 CONSTRAINT "HERITRIX_CRAWL_FILE_DETAI_PK" PRIMARY KEY ("ID")
   );
   
   
   CREATE SEQUENCE "CRAWLER_FILE_DETAILS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
   
   
   Insert into CRAWLER_CONFIG 
      	(ID,PROVIDER,WARC_FILE_LOCATION,DOWNLOAD_DIR_LOCATION,PROVIDER_BASE_URL,RSYNC_COMMAND,DELETE_FILES_FROM_DOWNLOAD_DIR) 
      values 
	(1,'MLR','/cmjp/EJournalCrawler/Heritrix/jobs/MonthlyLaborReview/latest/warcs','/cmjp/EJournalCrawler/Content','http://www.bls.gov','jstor@aa2ptcthumper05.ithaka.org:/csp_content/ongoing/backfileCSP/PAGE_IMAGES/MonthlyLaborReview','Y');
	
 
 ALTER TABLE CRAWLER_CONFIG ADD START_YEAR NUMBER;
 ALTER TABLE CRAWLER_CONFIG ADD START_VOLUME NUMBER;
 ALTER TABLE CRAWLER_CONFIG ADD START_ISSUE NUMBER;
 ALTER TABLE CRAWLER_CONFIG ADD START_SEASON VARCHAR2(255);
 
 
 UPDATE CRAWLER_CONFIG SET START_YEAR=2008 WHERE PROVIDER='MLR';
 COMMIT;