Insert into CRAWLER_CONFIG 
   	(ID,PROVIDER,WARC_FILE_LOCATION,DOWNLOAD_DIR_LOCATION,PROVIDER_BASE_URL,RSYNC_COMMAND,DELETE_FILES_FROM_DOWNLOAD_DIR) 
   values 
	(2,'CJS','/cmjd/Heritrix/Software/heritrix-3.2.0/jobs/CJS_NEW/20160105142935/warcs','/cmjd/Heritrix/temp','https://ejournals.library.ualberta.ca/index.php/CJS/issue/archive',
	'cmjq@aa2cmqa01.ithaka.org:/cmjq/Heritrix/dev_test_rsync/CJS/','Y');
	
Insert into CRAWLER_CONFIG 
   	(ID,PROVIDER,WARC_FILE_LOCATION,DOWNLOAD_DIR_LOCATION,PROVIDER_BASE_URL,RSYNC_COMMAND,DELETE_FILES_FROM_DOWNLOAD_DIR) 
   values 
	(3,'CJPH','/cmjd/Heritrix/Software/heritrix-3.2.0/jobs/CJPH_NEW/20160105143828/warcs','/cmjd/Heritrix/temp','http://journal.cpha.ca/index.php/cjph/issue/archive',
	'cmjq@aa2cmqa01.ithaka.org:/cmjq/Heritrix/dev_test_rsync/CJPH/','Y');	


ALTER TABLE CRAWLER_CONFIG ADD EXTRACTOR_NAME VARCHAR2(255);
ALTER TABLE CRAWLER_CONFIG ADD JOURNAL_CODE VARCHAR2(255);
ALTER TABLE CRAWLER_CONFIG ADD IS_ACTIVE CHAR(1);

UPDATE CRAWLER_CONFIG SET EXTRACTOR_NAME='MLRPDFExtractor' WHERE PROVIDER='MLR';
UPDATE CRAWLER_CONFIG SET EXTRACTOR_NAME='CJSPDFExtractor' WHERE PROVIDER='CJS';
UPDATE CRAWLER_CONFIG SET EXTRACTOR_NAME='CJSPDFExtractor' WHERE PROVIDER='CJPH';

UPDATE CRAWLER_CONFIG SET JOURNAL_CODE='monthlylaborreview' WHERE PROVIDER='MLR';
UPDATE CRAWLER_CONFIG SET JOURNAL_CODE='canajsocicahican' WHERE PROVIDER='CJS';
UPDATE CRAWLER_CONFIG SET JOURNAL_CODE='canajpublheal' WHERE PROVIDER='CJPH';

UPDATE CRAWLER_CONFIG SET IS_ACTIVE='Y';

COMMIT;