ALTER TABLE CRAWLER_CONFIG ADD START_YEAR NUMBER;
ALTER TABLE CRAWLER_CONFIG ADD START_VOLUME NUMBER;
ALTER TABLE CRAWLER_CONFIG ADD START_ISSUE NUMBER;
ALTER TABLE CRAWLER_CONFIG ADD START_SEASON VARCHAR2(255);