//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.02.13 at 02:58:03 PM EST 
//


package org.publisher.elsevier.xml.impl;

public class DatasetImpl implements org.publisher.elsevier.xml.Dataset, com.sun.xml.bind.RIElement, com.sun.xml.bind.JAXBObject, org.publisher.elsevier.xml.impl.runtime.UnmarshallableObject, org.publisher.elsevier.xml.impl.runtime.XMLSerializable, org.publisher.elsevier.xml.impl.runtime.ValidatableObject
{

    protected java.lang.String _Status;
    protected java.lang.String _Version;
    protected org.publisher.elsevier.xml.Date _Date;
    protected java.lang.String _Identifier;
    protected java.lang.String _Customer;
    protected com.sun.xml.bind.util.ListImpl _File;
    public final static java.lang.Class version = (org.publisher.elsevier.xml.impl.JAXBVersion.class);
    private final static org.relaxng.datatype.Datatype ___dt0 = com.sun.xml.bind.unmarshaller.DatatypeDeserializer.deserialize("\u00ac\u00ed\u0000\u0005sr\u0000\"com.sun.msv.datatype.xsd.TokenType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;L\u0000\btypeNameq\u0000~\u0000\u0005L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0005tokensr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001");
    private final static org.relaxng.datatype.Datatype ___dt1 = com.sun.xml.bind.unmarshaller.DatatypeDeserializer.deserialize("\u00ac\u00ed\u0000\u0005sr\u0000\"com.sun.msv.datatype.xsd.TokenType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;L\u0000\btypeNameq\u0000~\u0000\u0005L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0005tokensr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001");
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (org.publisher.elsevier.xml.Dataset.class);
    }

    public java.lang.String ____jaxb_ri____getNamespaceURI() {
        return "";
    }

    public java.lang.String ____jaxb_ri____getLocalName() {
        return "dataset";
    }

    public java.lang.String getStatus() {
        return _Status;
    }

    public void setStatus(java.lang.String value) {
        _Status = value;
    }

    public java.lang.String getVersion() {
        return _Version;
    }

    public void setVersion(java.lang.String value) {
        _Version = value;
    }

    public org.publisher.elsevier.xml.Date getDate() {
        return _Date;
    }

    public void setDate(org.publisher.elsevier.xml.Date value) {
        _Date = value;
    }

    public java.lang.String getIdentifier() {
        return _Identifier;
    }

    public void setIdentifier(java.lang.String value) {
        _Identifier = value;
    }

    public java.lang.String getCustomer() {
        return _Customer;
    }

    public void setCustomer(java.lang.String value) {
        _Customer = value;
    }

    protected com.sun.xml.bind.util.ListImpl _getFile() {
        if (_File == null) {
            _File = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
        }
        return _File;
    }

    public java.util.List getFile() {
        return _getFile();
    }

    public org.publisher.elsevier.xml.impl.runtime.UnmarshallingEventHandler createUnmarshaller(org.publisher.elsevier.xml.impl.runtime.UnmarshallingContext context) {
        return new org.publisher.elsevier.xml.impl.DatasetImpl.Unmarshaller(context);
    }

    public void serializeBody(org.publisher.elsevier.xml.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx6 = 0;
        final int len6 = ((_File == null)? 0 :_File.size());
        context.startElement("", "dataset");
        int idx_1 = idx6;
        {
            java.lang.Object o = _Status;
        }
        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Date), "Date");
        while (idx_1 != len6) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _File.get(idx_1 ++)), "File");
        }
        context.endNamespaceDecls();
        int idx_6 = idx6;
        context.startAttribute("", "customer");
        try {
            context.text(((java.lang.String) _Customer), "Customer");
        } catch (java.lang.Exception e) {
            org.publisher.elsevier.xml.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endAttribute();
        context.startAttribute("", "identifier");
        try {
            context.text(((java.lang.String) _Identifier), "Identifier");
        } catch (java.lang.Exception e) {
            org.publisher.elsevier.xml.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endAttribute();
        context.startAttribute("", "status");
        {
            java.lang.Object o = _Status;
            if (o instanceof java.lang.String) {
                try {
                    context.text(((java.lang.String) _Status), "Status");
                } catch (java.lang.Exception e) {
                    org.publisher.elsevier.xml.impl.runtime.Util.handlePrintConversionException(this, e, context);
                }
            } else {
                if (o instanceof java.lang.String) {
                    try {
                        context.text(((java.lang.String) _Status), "Status");
                    } catch (java.lang.Exception e) {
                        org.publisher.elsevier.xml.impl.runtime.Util.handlePrintConversionException(this, e, context);
                    }
                } else {
                    org.publisher.elsevier.xml.impl.runtime.Util.handleTypeMismatchError(context, this, "Status", o);
                }
            }
        }
        context.endAttribute();
        if (_Version!= null) {
            context.startAttribute("", "version");
            try {
                context.text(((java.lang.String) _Version), "Version");
            } catch (java.lang.Exception e) {
                org.publisher.elsevier.xml.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Date), "Date");
        while (idx_6 != len6) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _File.get(idx_6 ++)), "File");
        }
        context.endAttributes();
        context.childAsBody(((com.sun.xml.bind.JAXBObject) _Date), "Date");
        while (idx6 != len6) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _File.get(idx6 ++)), "File");
        }
        context.endElement();
    }

    public void serializeAttributes(org.publisher.elsevier.xml.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx6 = 0;
        final int len6 = ((_File == null)? 0 :_File.size());
    }

    public void serializeURIs(org.publisher.elsevier.xml.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx6 = 0;
        final int len6 = ((_File == null)? 0 :_File.size());
    }

    public java.lang.Class getPrimaryInterface() {
        return (org.publisher.elsevier.xml.Dataset.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
+"\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv."
+"grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000"
+"\fcontentModelt\u0000 Lcom/sun/msv/grammar/Expression;xr\u0000\u001ecom.sun."
+"msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Lj"
+"ava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0003xppp\u0000sr\u0000\u001fcom.sun.msv.gra"
+"mmar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.BinaryExp"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1q\u0000~\u0000\u0003L\u0000\u0004exp2q\u0000~\u0000\u0003xq\u0000~\u0000\u0004ppsq\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007pps"
+"q\u0000~\u0000\u0007ppsq\u0000~\u0000\u0007ppsr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0003L\u0000\tnameClassq\u0000~\u0000\u0001xq\u0000~\u0000\u0004ppsr\u0000\u001bcom.sun.msv.gramma"
+"r.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L"
+"\u0000\u0006exceptq\u0000~\u0000\u0003L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0004pp"
+"sr\u0000-com.sun.msv.datatype.xsd.NormalizedStringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xr\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlway"
+"sValidxr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'c"
+"om.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespac"
+"eUrit\u0000\u0012Ljava/lang/String;L\u0000\btypeNameq\u0000~\u0000\u0019L\u0000\nwhiteSpacet\u0000.Lco"
+"m/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w"
+"3.org/2001/XMLSchemat\u0000\u0010normalizedStringsr\u00004com.sun.msv.datat"
+"ype.xsd.WhiteSpaceProcessor$Replace\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.ms"
+"v.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun."
+"msv.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004pps"
+"r\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0019L\u0000"
+"\fnamespaceURIq\u0000~\u0000\u0019xpt\u0000\u0005CDATAt\u0000\u0000sr\u0000#com.sun.msv.grammar.Simpl"
+"eNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0019L\u0000\fnamespaceURIq\u0000~\u0000\u0019xr"
+"\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\bcustomerq\u0000~\u0000&"
+"sq\u0000~\u0000\u000eppq\u0000~\u0000\u0013sq\u0000~\u0000\'t\u0000\nidentifierq\u0000~\u0000&sq\u0000~\u0000\u000eppsr\u0000\u001dcom.sun.msv"
+".grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\bppsr\u0000\u001ccom.sun.msv.grammar"
+".ValueExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtq\u0000~\u0000\u0011L\u0000\u0004nameq\u0000~\u0000\u0012L\u0000\u0005valuet\u0000\u0012Ljava/l"
+"ang/Object;xq\u0000~\u0000\u0004sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000"
+"psr\u0000\"com.sun.msv.datatype.xsd.TokenType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0015q\u0000~\u0000"
+"\u001ct\u0000\u0005tokensr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Co"
+"llapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001f\u0001sq\u0000~\u0000#t\u0000\u000bENUMERATIONq\u0000~\u0000&t\u0000\fAnnounce"
+"mentsq\u0000~\u00001q\u0000~\u00005pq\u0000~\u00007q\u0000~\u0000;t\u0000\fConfirmationsq\u0000~\u0000\'t\u0000\u0006statusq\u0000~\u0000"
+"&sq\u0000~\u0000/ppsq\u0000~\u0000\u000eq\u0000~\u00005psq\u0000~\u00001ppq\u0000~\u0000\u001bsq\u0000~\u0000#q\u0000~\u0000%q\u0000~\u0000&t\u0000.Network"
+" Dataset Announcement/Confirmation v1.0sq\u0000~\u0000\'t\u0000\u0007versionq\u0000~\u0000&"
+"sr\u00000com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0000xq\u0000~\u0000\u0004sq\u0000~\u00004\u0001q\u0000~\u0000Jsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000/ppsr\u0000 com.sun.msv.gramma"
+"r.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0003xq\u0000~\u0000\u0004q\u0000~\u00005psq\u0000~\u0000\u000eq\u0000~\u00005psr\u00002com.sun.msv.g"
+"rammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004q\u0000~\u0000Kq"
+"\u0000~\u0000Ssr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000(q\u0000~"
+"\u0000Jsq\u0000~\u0000\'t\u0000\u001forg.publisher.elsevier.xml.Datet\u0000+http://java.sun"
+".com/jaxb/xjc/dummy-elementssq\u0000~\u0000Nppsq\u0000~\u0000\u0000pp\u0000sq\u0000~\u0000/ppsq\u0000~\u0000Nq"
+"\u0000~\u00005psq\u0000~\u0000\u000eq\u0000~\u00005pq\u0000~\u0000Sq\u0000~\u0000Uq\u0000~\u0000Jsq\u0000~\u0000\'t\u0000\u001forg.publisher.elsev"
+"ier.xml.Fileq\u0000~\u0000Xsq\u0000~\u0000\'t\u0000\u0007datasetq\u0000~\u0000&sr\u0000\"com.sun.msv.gramma"
+"r.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/gramma"
+"r/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.Expres"
+"sionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersionL\u0000\u0006par"
+"entt\u0000$Lcom/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u0000\u000b\u0001pq\u0000~\u0000\rq\u0000~\u0000\n"
+"q\u0000~\u0000Yq\u0000~\u0000Mq\u0000~\u0000[q\u0000~\u0000Bq\u0000~\u0000\u000bq\u0000~\u0000Pq\u0000~\u0000\\q\u0000~\u0000\tq\u0000~\u0000\fx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends org.publisher.elsevier.xml.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(org.publisher.elsevier.xml.impl.runtime.UnmarshallingContext context) {
            super(context, "-----------------");
        }

        protected Unmarshaller(org.publisher.elsevier.xml.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return org.publisher.elsevier.xml.impl.DatasetImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        attIdx = context.getAttribute("", "identifier");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 7;
                            eatText1(v);
                            continue outer;
                        }
                        break;
                    case  10 :
                        attIdx = context.getAttribute("", "version");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 13;
                            eatText2(v);
                            continue outer;
                        }
                        state = 13;
                        continue outer;
                    case  13 :
                        if (("date" == ___local)&&("" == ___uri)) {
                            _Date = ((org.publisher.elsevier.xml.impl.DateImpl) spawnChildFromEnterElement((org.publisher.elsevier.xml.impl.DateImpl.class), 14, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  7 :
                        attIdx = context.getAttribute("", "status");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                    case  14 :
                        if (("file" == ___local)&&("" == ___uri)) {
                            _getFile().add(((org.publisher.elsevier.xml.impl.FileImpl) spawnChildFromEnterElement((org.publisher.elsevier.xml.impl.FileImpl.class), 15, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        break;
                    case  1 :
                        attIdx = context.getAttribute("", "customer");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 4;
                            eatText3(v);
                            continue outer;
                        }
                        break;
                    case  16 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  15 :
                        if (("file" == ___local)&&("" == ___uri)) {
                            _getFile().add(((org.publisher.elsevier.xml.impl.FileImpl) spawnChildFromEnterElement((org.publisher.elsevier.xml.impl.FileImpl.class), 15, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        break;
                    case  0 :
                        if (("dataset" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Identifier = com.sun.xml.bind.WhiteSpaceProcessor.replace(value);
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Version = com.sun.xml.bind.WhiteSpaceProcessor.replace(value);
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Customer = com.sun.xml.bind.WhiteSpaceProcessor.replace(value);
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        attIdx = context.getAttribute("", "identifier");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 7;
                            eatText1(v);
                            continue outer;
                        }
                        break;
                    case  10 :
                        attIdx = context.getAttribute("", "version");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 13;
                            eatText2(v);
                            continue outer;
                        }
                        state = 13;
                        continue outer;
                    case  7 :
                        attIdx = context.getAttribute("", "status");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  1 :
                        attIdx = context.getAttribute("", "customer");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 4;
                            eatText3(v);
                            continue outer;
                        }
                        break;
                    case  16 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  15 :
                        if (("dataset" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 16;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        if (("identifier" == ___local)&&("" == ___uri)) {
                            state = 5;
                            return ;
                        }
                        break;
                    case  10 :
                        if (("version" == ___local)&&("" == ___uri)) {
                            state = 11;
                            return ;
                        }
                        state = 13;
                        continue outer;
                    case  7 :
                        if (("status" == ___local)&&("" == ___uri)) {
                            state = 8;
                            return ;
                        }
                        break;
                    case  1 :
                        if (("customer" == ___local)&&("" == ___uri)) {
                            state = 2;
                            return ;
                        }
                        break;
                    case  16 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        attIdx = context.getAttribute("", "identifier");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 7;
                            eatText1(v);
                            continue outer;
                        }
                        break;
                    case  10 :
                        attIdx = context.getAttribute("", "version");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 13;
                            eatText2(v);
                            continue outer;
                        }
                        state = 13;
                        continue outer;
                    case  7 :
                        attIdx = context.getAttribute("", "status");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  6 :
                        if (("identifier" == ___local)&&("" == ___uri)) {
                            state = 7;
                            return ;
                        }
                        break;
                    case  3 :
                        if (("customer" == ___local)&&("" == ___uri)) {
                            state = 4;
                            return ;
                        }
                        break;
                    case  1 :
                        attIdx = context.getAttribute("", "customer");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            state = 4;
                            eatText3(v);
                            continue outer;
                        }
                        break;
                    case  16 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  9 :
                        if (("status" == ___local)&&("" == ___uri)) {
                            state = 10;
                            return ;
                        }
                        break;
                    case  12 :
                        if (("version" == ___local)&&("" == ___uri)) {
                            state = 13;
                            return ;
                        }
                        break;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  4 :
                            attIdx = context.getAttribute("", "identifier");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 7;
                                eatText1(v);
                                continue outer;
                            }
                            break;
                        case  10 :
                            attIdx = context.getAttribute("", "version");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 13;
                                eatText2(v);
                                continue outer;
                            }
                            state = 13;
                            continue outer;
                        case  8 :
                            if (___dt0 .isValid(value, null)) {
                                state = 9;
                                eatText4(value);
                                return ;
                            }
                            if (___dt1 .isValid(value, null)) {
                                state = 9;
                                eatText5(value);
                                return ;
                            }
                            break;
                        case  7 :
                            attIdx = context.getAttribute("", "status");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                        case  2 :
                            state = 3;
                            eatText3(value);
                            return ;
                        case  1 :
                            attIdx = context.getAttribute("", "customer");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                state = 4;
                                eatText3(v);
                                continue outer;
                            }
                            break;
                        case  16 :
                            revertToParentFromText(value);
                            return ;
                        case  11 :
                            state = 12;
                            eatText2(value);
                            return ;
                        case  5 :
                            state = 6;
                            eatText1(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Status = com.sun.xml.bind.WhiteSpaceProcessor.collapse(value);
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText5(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Status = com.sun.xml.bind.WhiteSpaceProcessor.collapse(value);
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
