insert into cat_roles (id, cat_name) values ( 'System', 'System' );
insert into cat_roles (id, cat_name) values ( 'CD Publisher Relations', 'CD Publisher Relations' );
insert into cat_roles (id, cat_name) values ( 'CD Negotiations', 'CD Negotiations' );
insert into cat_roles (id, cat_name) values ( 'Librarians', 'Librarians' );
insert into cat_roles (id, cat_name) values ( 'Acquisitions', 'Acquisitions' );
insert into cat_roles (id, cat_name) values ( 'Inventory', 'Inventory' );
insert into cat_roles (id, cat_name) values ( 'CM Arch. Comp', 'CM Arch. Comp' );
insert into cat_roles (id, cat_name) values ( 'CM Management', 'CM Management' );
insert into cat_roles (id, cat_name) values ( 'DRT', 'DRT' );
insert into cat_roles (id, cat_name) values ( 'ADMIN', 'ADMIN' );
insert into cat_roles (id, cat_name) values ( 'QC', 'QC' );
