
-- try 2:
DROP TABLE "CAT_ROLLUPS_SETS"
;
CREATE TABLE "CAT_ROLLUPS_SETS" (
"ID" VARCHAR2(255) NOT NULL ENABLE,
"SETS_ID" VARCHAR2(255) NOT NULL ENABLE,
"PUBLISHER_VALUE" VARCHAR2(512) ,
"LICENSOR_VALUE" VARCHAR2(512) ,
"SELECTION_RIGHTS_VALUE" VARCHAR2(512) ,
"PRODUCTION_STATUS_VALUE" VARCHAR2(512) ,
"WALL_VALUE" VARCHAR2(512) ,
"DISCIPLINES_VALUE" VARCHAR2(512) ,
"RIDER_VALUE" VARCHAR2(512) ,
"COLLECTIONS_LIST_VALUE" VARCHAR2(512) ,
"INVN_DECLINE_REASON_VALUE" VARCHAR2(512) ,
"INVN_NOTE_VALUE" VARCHAR2(512) ,
"PARTN_DATE_VALUE" VARCHAR2(512) ,
"INI_REL_DEADLINE_VALUE" VARCHAR2(512) ,
"SIGNING_DEADLINE_VALUE" VARCHAR2(512) ,
"INI_REL_DATE_ACTL_VALUE" VARCHAR2(512) ,
"INI_REL_DATE_SCHD_VALUE" VARCHAR2(512) ,
"INI_REL_DATE_PRJD_VALUE" VARCHAR2(512) ,
"PRIMARY_SIG_DATE_COMPLETED" VARCHAR2(512) ,
"DATE_SENT_TO_VENDOR_VALUE" VARCHAR2(512) ,
"INVN_DATE_SENT_VALUE" VARCHAR2(512) ,
"INVN_COMPLETED_DATE_VALUE" VARCHAR2(512) ,
"DECLINE_DATE_VALUE" VARCHAR2(512) ,
"CNT_INVN_ACCEPTED" VARCHAR2(512) ,
"CNT_INVN_DECLINED" VARCHAR2(512) ,
"CNT_INVN_ACTIVE" VARCHAR2(512) ,
"CMPTS_LIST" VARCHAR2(1024) ,
PRIMARY KEY( "ID" )
)
;

ALTER TABLE "CAT_ROLLUPS_SETS"
    ADD CONSTRAINT "CAT_ROLLUPS_SETS_FK" FOREIGN KEY ( "SETS_ID" ) REFERENCES "CAT_SETS" ( "ID" )
    ;

    
    
DROP TABLE "CAT_ROLLUPS_CMPTS";

CREATE TABLE "CAT_ROLLUPS_CMPTS" (
"ID" VARCHAR2(255) NOT NULL ENABLE,
"CMPTS_ID" VARCHAR2(255) NOT NULL ENABLE,
"DISCIPLINES_VALUE" VARCHAR2(512),
"SELECTION_RIGHTS_VALUE" VARCHAR2(512),
"LICENSOR_VALUE" VARCHAR2(512),
"PUBLISHER_VALUE" VARCHAR2(512),
"RIDERS_VALUE" VARCHAR2(512),
"COLLECTIONS_VALUE" VARCHAR2(512),
"SETS_VALUE" VARCHAR2(512),
PRIMARY KEY( "ID" )
)
;

ALTER TABLE "CAT_ROLLUPS_CMPTS"
    ADD CONSTRAINT "CAT_ROLLUPS_CMPTS_FK" FOREIGN KEY ( "CMPTS_ID" ) REFERENCES "CAT_CMPTS" ( "ID" )
    ;
    