insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('ablondin', 'Acquisitions');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('aray', 'CD Negotiations');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('astanley', 'Librarians');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('bchin', 'CD Negotiations');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('bpezet', 'Librarians');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('cmezuk', 'CM Arch. Comp');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('craudenbush', 'DRT');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('dhajjar', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('ebetwee', 'Librarians');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('echaney', 'Inventory');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('ekenaga', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('eknapp', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('hreid', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('jglover', 'Acquisitions');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('jhovis', 'CD Publisher Relations');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('jkiplinger', 'Librarians');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('jkiplinger', 'Acquisitions');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('jkiplinger', 'Inventory');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('jkiplinger', 'CM Arch. Comp');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('jkiplinger', 'CM Management');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('jkiplinger', 'DRT');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('jkiplinger', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('jponder', 'Librarians');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('jscroggins', 'CM Arch. Comp');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('jsherwin', 'CD Negotiations');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('kaufdemberge', 'Librarians');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('kharto', 'CD Publisher Relations');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('kharto', 'DRT');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('landrews', 'Inventory');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('landrews', 'CM Management');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('alarson', 'CD Negotiations');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('larson', 'CD Negotiations');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('lmikulka', 'CD Negotiations');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('lsarmiento', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('mborton', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('mpugh', 'CD Publisher Relations');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nmurray', 'Librarians');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nmurray', 'CM Management');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nmurray', 'DRT');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nmurray', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nvand', 'Acquisitions');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nvand', 'Inventory');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nvand', 'CM Arch. Comp');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nvand', 'CM Management');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nvand', 'DRT');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nvand', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('panchill', 'Acquisitions');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('rross', 'Librarians');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('sanderson', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('sblacksher', 'Inventory');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('scunningham', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('sgarewal', 'Librarians');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('sheminger', 'Librarians');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('sheminger', 'DRT');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('shifra', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('skim', 'CD Negotiations');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('tlehnerer', 'Inventory');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('tokoh', 'CD Negotiations');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('tquigley', 'CM Arch. Comp');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('tquigley', 'CM Management');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('vgardner', 'CM Arch. Comp');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('vgardner', 'CM Management');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('vgardner', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('wwiitala', 'CM Arch. Comp');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('pelkins', 'Inventory');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nkerr', 'CD Publisher Relations');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nkerr', 'CD Negotiations');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nkerr', 'Librarians');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nkerr', 'Acquisitions');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nkerr', 'Inventory');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nkerr', 'CM Arch. Comp');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nkerr', 'CM Management');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nkerr', 'DRT');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nkerr', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nkerr', 'ADMIN');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('schalla', 'CD Publisher Relations');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('schalla', 'CD Negotiations');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('schalla', 'Librarians');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('schalla', 'Acquisitions');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('schalla', 'Inventory');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('schalla', 'CM Arch. Comp');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('schalla', 'CM Management');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('schalla', 'DRT');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('schalla', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('schalla', 'ADMIN');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('vcheruku', 'CD Publisher Relations');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('vcheruku', 'CD Negotiations');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('vcheruku', 'Librarians');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('vcheruku', 'Acquisitions');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('vcheruku', 'Inventory');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('vcheruku', 'CM Arch. Comp');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('vcheruku', 'CM Management');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('vcheruku', 'DRT');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('vcheruku', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('vcheruku', 'ADMIN');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('bkulkarni', 'CD Publisher Relations');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('bkulkarni', 'CD Negotiations');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('bkulkarni', 'Librarians');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('bkulkarni', 'Acquisitions');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('bkulkarni', 'Inventory');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('bkulkarni', 'CM Arch. Comp');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('bkulkarni', 'CM Management');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('bkulkarni', 'DRT');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('bkulkarni', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('bkulkarni', 'ADMIN');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('sranganathan', 'CD Publisher Relations');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('sranganathan', 'CD Negotiations');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('sranganathan', 'Librarians');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('sranganathan', 'Acquisitions');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('sranganathan', 'Inventory');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('sranganathan', 'CM Arch. Comp');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('sranganathan', 'CM Management');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('sranganathan', 'DRT');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('sranganathan', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('sranganathan', 'ADMIN');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('tgreen', 'CD Publisher Relations');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('tgreen', 'CD Negotiations');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('tgreen', 'Librarians');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('tgreen', 'Acquisitions');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('tgreen', 'Inventory');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('tgreen', 'CM Arch. Comp');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('tgreen', 'CM Management');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('tgreen', 'DRT');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('tgreen', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('tgreen', 'ADMIN');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('whoward', 'CD Publisher Relations');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('whoward', 'CD Negotiations');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('whoward', 'Librarians');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('whoward', 'Acquisitions');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('whoward', 'Inventory');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('whoward', 'CM Arch. Comp');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('whoward', 'CM Management');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('whoward', 'DRT');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('whoward', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('whoward', 'ADMIN');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('skadirvel', 'ADMIN');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('hmanduva', 'ADMIN');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('jhirschman', 'ADMIN');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nfrota', 'CD Publisher Relations');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nfrota', 'CD Negotiations');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nfrota', 'Librarians');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nfrota', 'Acquisitions');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nfrota', 'Inventory');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nfrota', 'CM Arch. Comp');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nfrota', 'CM Management');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nfrota', 'DRT');
--insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nfrota', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('nfrota', 'ADMIN');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('mdavid', 'CD Publisher Relations');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('mdavid', 'CD Negotiations');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('mdavid', 'Librarians');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('mdavid', 'Acquisitions');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('mdavid', 'Inventory');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('mdavid', 'CM Arch. Comp');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('mdavid', 'CM Management');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('mdavid', 'DRT');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('mdavid', 'QC');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('mdavid', 'ADMIN');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('jrogowski ', 'ADMIN');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('rrajan', 'CD Negotiations');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('mpugh', 'CD Negotiations');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('kharto', 'CD Negotiations');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ('anicholson', 'CM Arch. Comp');
insert into cat_user_roles ( cat_user_id, cat_roles_id ) values ( 'jprzybylski', 'CD Negotiations');
